scopes = ["hub", "remote", "user", "license", "output", "config"]
types = ["feat", "chore", "fix", "docs", "style", "refactor", "perf", "test", "build", "ci", "revert"]
me = "hackia"
repository = "uvd"
